### ISSUE TITLE
gdb 调试如何查看物理内存

### ISSUE THREAD

**Issue by shiweiwww** [rcore-os/rCore-Tutorial#101]

**Comment by luojia65** [comment]
我暂时实践下来似乎没法看的，好像只能直接看虚拟内存。的确这部分给调试页表带来很大的不方便

**Comment by leonardodalinky** [comment]
https://www.qemu.org/docs/master/system/gdb.html
引用一下原文

> If you want to examine/change the physical memory you can set the gdbstub to work with the physical memory rather with the virtual one.
> The memory mode can be checked by sending the following command:
>     `maintenance packet qqemu.PhyMemMode`
> This will return either 0 or 1, 1 indicates you are currently in the physical memory mode.
>     `maintenance packet Qqemu.PhyMemMode:1`
> This will change the memory mode to physical memory.
>     `maintenance packet Qqemu.PhyMemMode:0`
> This will change it back to normal memory mode.

好像可以通过gdb连接qemu然后设置模式来调整内存访问模式。建议翻一下qemu对gdb支持的相关文档。

**Comment by shiweiwww** [comment]
好的，多谢多谢
