### ISSUE TITLE
关于lab2实验题的堆的递归定义

### ISSUE THREAD

**Issue by stellarkey** [rcore-os/rCore-Tutorial#108]
# 关于lab2实验题的堆的递归定义

题目链接：https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-2/practice.html

题面：

![图片](https://user-images.githubusercontent.com/38290992/88413799-6524dc80-ce0e-11ea-8de6-09cf8f3b0a9c.png)

这个地方用“循环”这个词似乎不太准确。。用递归定义是否会更好？

以及，这样执行一段时间以后是否会爆栈？

**Comment by VitalyAnkh** [comment]
“循环”在这里只是一个通俗说法吧，要说是“递归”，也不符合递归的定义

> 以及，这样执行一段时间以后是否会爆栈？

在**堆**上分配内存给一个数据结构，怎么会爆**栈**呢

**Comment by stellarkey** [comment]
> 
> 
> “循环”在这里只是一个通俗说法吧，要说是“递归”，也不符合递归的定义
> 
> > 以及，这样执行一段时间以后是否会爆栈？
> 
> 在**堆**上分配内存给一个数据结构，怎么会爆**栈**呢


在堆上分配内存，需要调用内存分配函数，而函数信息需要占空间储存在栈上，而每次分配都需要额外重新之前的内存分配，形成新的函数栈，怎么不会爆栈呢？

这样的过程为什么不符合递归的定义呢？QAQ

**Comment by dingiso** [comment]
我的理解是，我觉得 “循环” 这个词用的比较通俗，是正确的，递归确实不是他想表达的意思，递归是与自身的关系，但是实际上这是两个实体间的关系。

我更习惯用 `死锁` 来表达这种情况 

- vec 需要调用 我们实现的堆 和分配器
- 而堆和分配器需要使用我们的 vec

这种互相需要的关系，确实可以理解成是一种 不断循环调用，但是我觉得死锁可以拓展定义成这样

**Comment by greatoyster** [comment]
感觉用循环依赖来描述也不错

**Comment by stellarkey** [comment]
感觉各位解释的很到位了，thanks
