### ISSUE TITLE
关于lab2 线段树分配器的DEBUG问题

### ISSUE THREAD

**Issue by stellarkey** [rcore-os/rCore-Tutorial#109]
如题，写完以后虽然可以通过编译并运行，但是，如何验证Allocator的正确性呢？

`println!` 宏因为禁用 std 而不能使用，对这一个 Allocator 进行单独的测试可行吗？Rust 是否支持类似 Java 一样的单个文件的测试（每个 Java 文件都是一个类，可以单独定义 main 函数并调试运行）？

大家都是怎么测试的？只能在整个项目的 `main.rs` 里面测试吗？

**Comment by freheit889** [comment]
我是单写出来然后测试的  自己alloc 然后dealloc  打印出看是否正确

**Comment by yukiiiteru** [comment]
可以用单元测试，在模块前加 `#[cfg(test)]`，然后在模块内的函数前面写 `#[test]`，函数内用 `assert` 或者 `assert_eq` 语句判断是否正确执行，然后运行 `cargo test` 进行测试

**Comment by Tuyixiang** [comment]
确实我们没有充足时间来为所有实验添加测试，非常欢迎大家如果自己写了比较好的单元测试发到 PR

**Comment by stellarkey** [comment]
好的，谢谢
