### ISSUE TITLE
环境部署时还需要其他两个依赖执行

### ISSUE THREAD

**Issue by Akelio-zhang** [rcore-os/rCore-Tutorial#118]
### 涉及文件
`os/Makefile`

### 遇到问题
编译过程中提示can't find crate for `core`，需要执行`rustup target add riscv64imac-unknown-none-elf`

rust-objcopy需要提前安装
```
$ cargo install cargo-binutils
$ rustup component add llvm-tools-preview
```

**Comment by Tuyixiang** [comment]
[实验指导](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-0/guide/part-5.html)里面写了
