### ISSUE TITLE
实验三 Mapping 中 mapped_pairs 作用

### ISSUE THREAD

**Issue by kiyoakii** [rcore-os/rCore-Tutorial#119]
### 实验三 `Mapping` 中 `mapped_pairs` 作用

`mapped_pairs` 相当于在操作系统堆空间中把页表又存了一份，这有什么意义吗？（真的想了非常久，同时在代码仓库中全局搜索 「mapped_pairs」，发现除了创建和删除某个页表时有对其的修改操作，其它均没有使用到。）

**Comment by wyfcyx** [comment]
`mapped_pairs` 除了可以方便的找到一个虚拟页被映射到哪个物理页帧，无需手动查页表；另一个作用是提供了一个地方让 `FrameTracker` 可以挂在下面，延长了它的生命周期。这样，当 `Mapping` 被回收的时候，下面挂着的各个 `FrameTracker` 也会被 drop，从而在 FrameAllocator 中释放掉先前分配的那些用于存储*数据*的物理页帧。那么用于存储*页表*的那些物理页帧呢？它们则是被挂在 `page_table` 字段里面的 `PageTableTracker` 里面的 `FrameTracker` 下面。因此，一旦一个 `Mapping` 的生命周期结束，那些用于存储页表映射和存储数据（通常是用于进程的代码、数据、栈）的物理页帧都会在 FrameAllocator 中释放，从而可以重新被分配出去。

**Comment by kiyoakii** [comment]
感谢回答，我明白了，就是更好地利用 Rust 的特性来自动处理。那下一个问题是...是不管用什么语言实现操作系统都会有类似的冗余问题吗？（之前没看过其它的实现）

**Comment by wyfcyx** [comment]
系统的设计没有银弹。这是一个包含安全性、源码复杂性、性能、内存占用等多方面的权衡，无论对于哪一方面进行优化都有可能导致其他方面的退化。而采用 Rust 语言则从目前来看是一个很好的权衡，这是由于 Rust 语言兼具高性能、安全性与强表达能力的特性。而这里的设计也未必是冗余，而可以看成用一点内存占用自动避免了内存溢出的风险并使源码变得更加简单。

**Comment by kiyoakii** [comment]
确实如此，感谢回答。
