### ISSUE TITLE
Symbol format `elf64-littleriscv' unknown.

### ISSUE THREAD

**Issue by em2046** [rcore-os/rCore-Tutorial#123]
### 涉及文件
rCore-Tutorial/os/target/riscv64imac-unknown-none-elf/debug/os

### 相关段落
GDB 调试方法* 
在 GDB 中执行 file target/riscv64imac-unknown-none-elf/debug/os 来加载未被 strip 过的内核文件中的各种符号

### 遇到问题
gdb中执行加载符号时出现错误：
I'm sorry, Dave, I can't do that.  Symbol format `elf64-littleriscv' unknown.

操作系统：macOS Catalina 10.15.7 (19H15)
软件版本：
riscv64-unknown-elf-gdb: GNU gdb (GDB) 10.1 --host=x86_64-apple-darwin19.6.0 --target=riscv64-unknown-elf
qemu-system-riscv64: QEMU emulator version 5.1.0

Big Sur也有此问题，但虚拟机中的Ubuntu 20.04是好的

**Comment by em2046** [comment]
macOS Big Sur安装https://github.com/riscv/homebrew-riscv 后解决此问题
如果已经手动用源码构建过gdb，安装homebrew-riscv时会报错并提示文件冲突，删除冲突的文件后，重新安装homebrew-riscv即可
homebrew-riscv自带的gdb是9.1版本。我尝试源码构建的gdb是10.1与9.2版本

**Comment by em2046** [comment]
如果使用homebrew-riscv中的riscv64-unknown-elf-gdb出现警告，提示缺少python，按下方的方法复制下文件即可解决

https://github.com/riscv/homebrew-riscv/issues/39

**Comment by em2046** [comment]
Ubuntu下使用gdb 10.1可能会出现寄存器Registers无法在gdb-dashboard默认布局中显示，使用9.1版本即可解决

**Comment by kiyoakii** [comment]
@em2046 手动换回 gdb 9.1 解决了我近期遇到的全部问题，非常感谢。

**Comment by xkkker** [comment]
请问如何将gdb降到9.1版本？

**Comment by kiyoakii** [comment]
@xkkker 通过搜索 homebrew install older edition 关键词，可以查到此结果：[How to Install an Older Brew Package](https://itnext.io/how-to-install-an-older-brew-package-add141e58d32)
