### ISSUE TITLE
lab2 堆分配越界

### ISSUE THREAD

**Issue by generalibm** [rcore-os/rCore-Tutorial#129]
先看代码
```rust
pub extern "C" fn rust_main() {
    interrupt::init();
    memory::init();
    
    let mut vec = Vec::new();
    for i in 0..(KERNEL_HEAP_SIZE) {
        vec.push(i);
    }
    assert_eq!(vec.len(), (KERNEL_HEAP_SIZE));
    for (i, value) in vec.into_iter().enumerate() {
        assert_eq!(value, i);
    }
    println!("end of main");
    panic!();
}
```
这段代码会导致堆内存分配失败。

可以看到，在 `os/src/memory/heap.rs` 中有两处操作
1. 12行处 `static mut HEAP_SPACE: [u8; KERNEL_HEAP_SIZE] = [0; KERNEL_HEAP_SIZE];`
1. 27行处 `HEAP.lock().init(HEAP_SPACE.as_ptr() as usize, KERNEL_HEAP_SIZE);`

前者使用 `u8`，后者使用 `usize`，但是大小都是 `KERNEL_HEAP_SIZE`。

### 涉及文件
- `os/src/memory/heap.rs`

**Comment by wyfcyx** [comment]
``KERNEL_HEAP_SIZE`` 的单位为字节，而代码中却要在堆中存放这么多 8 个字节，本来就会造成堆空间不足。即使要存放这么多单个字节也是做不到的，因为堆内存分配要考虑到一些对齐需求，而且管理堆空间的数据结构也同样存放在堆空间里面，都会导致可实际用来分配的大小小于堆空间的大小。

**Comment by generalibm** [comment]
@wyfcyx 谢谢，现在明白了，之前忽视了这个问题。
