### ISSUE TITLE
Can not boot kernel: OpenSBI does not lead kernel to _start

### ISSUE THREAD

**Issue by YanB25** [rcore-os/rCore-Tutorial#136]
### 涉及文件
Unknown.

### 相关段落
Unknown

### 遇到问题
The kernel never enters `_start` (or `0x80200000`).

# How to reproduce

``` bash
cd os; make run
```

and the program is blocked with the following outputs

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s

OpenSBI v0.8
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

Platform Name       : riscv-virtio,qemu
Platform Features   : timer,mfdeleg
Platform HART Count : 1
Boot HART ID        : 0
Boot HART ISA       : rv64imafdcsu
BOOT HART Features  : pmp,scounteren,mcounteren,time
BOOT HART PMP Count : 16
Firmware Base       : 0x80000000
Firmware Size       : 92 KB
Runtime SBI Version : 0.2

MIDELEG : 0x0000000000000222
MEDELEG : 0x000000000000b109
PMP0    : 0x0000000080000000-0x000000008001ffff (A)
PMP1    : 0x0000000000000000-0xffffffffffffffff (A,R,W,X
```

# Expected behavior

I expect the program will enter `rust_main` (in `main.rs`) and print `Hello, rCore-Tutorial!` to the console. However, the program is blocked forever.

If running with `make debug`: the kernel gets stuck around somewhere like `0x0000000080000540 in ?? ()`. I expect OpenSBI will lead the kernel to `0x80200000` but the kernel never reaches there.

# Environment
Machine OS: Ubuntu 20.04.2 LTS
QEMU: 5.2.50 (v5.2.0-2331-g7ef8134565)
P.S. I'm currently unable to build qemu 5.0.x (the exact version used in the tutorial), but I can try if necessary.

**Comment by NaviVoid** [comment]
use other version of openSBI, 0.9 works fine for me

**Comment by YanB25** [comment]
After switching back to **qemu 5.0.1** (with OpenSBI v0.6), the code run correctly.

The reason why I can not build qemu 5.0.1 is due to the incompatibility of clang/clang++. gcc and g++ work well.
I also tried to use the latest qemu with a different version of OpenSBI, but fail.

Thanks

**Comment by NaviVoid** [comment]
> After switching back to **qemu 5.0.1** (with OpenSBI v0.6), the code run correctly.
> 
> The reason why I can not build qemu 5.0.1 is due to the incompatibility of clang/clang++. gcc and g++ work well.
> I also tried to use the latest qemu with a different version of OpenSBI, but fail.
> 
> Thanks

You can use `qemu-system-riscv64 -bios path/to/fw_payload.bin` to use different version of openSBI, no need to touch qemu
