### ISSUE TITLE
lab 2中关于堆上内存回收的一个问题

### ISSUE THREAD

**Issue by kamome1037** [rcore-os/rCore-Tutorial#147]
### lab 2中关于堆上内存回收的一个问题
大致描述问题
> “在堆上的内存回收出现行为不一致”

在进行lab 2的时候，我对堆上的内存回收机制进行了调试，在如下代码
```rust
let mut vec = Vec::new();
for i in 0..100 {
    vec.push(i);
}
```
输出了符合预期的结果
![图片](https://user-images.githubusercontent.com/73805584/125193780-e0caa400-e280-11eb-8ec2-63f396944647.png)
内存正常地申请回收了

可是当主函数执行到物理页分配部分的代码时
```rust
for _ in 0..2 {
        let frame_0 = match memory::frame::FRAME_ALLOCATOR.lock().alloc() {
            Result::Ok(frame_tracker) => frame_tracker,
            Result::Err(err) => panic!("{}", err),
        };
        let frame_1 = match memory::frame::FRAME_ALLOCATOR.lock().alloc() {
            Result::Ok(frame_tracker) => frame_tracker,
            Result::Err(err) => panic!("{}", err),
        };
        println!("{} and {}", frame_0.address(), frame_1.address());
}
panic!("end of rust_main");
```
输出的结果如下
![图片](https://user-images.githubusercontent.com/73805584/125193807-fcce4580-e280-11eb-97ab-4c0408f1a1a2.png)

这里发生的内存分配和回收是由于在使用栈结构实现分配器的时候，用到了Vec，带来了动态的内存分配，但是让我疑惑的是，对于第一种情况下，Vec申请的内存最终都被回收了，而第二种情况下可以看到StackedAllocator中的Vec申请的一块大小为64的内存还没来得及回收，主函数就退出了，为什么这两种情况下Vec内存回收的机制不一样，希望有人能解答我的这个疑问，感谢。

**Comment by MorningGloryy** [comment]
from：batman
两个alloc dealloc是有点不一样，但都是伙伴系统，这个网站可能会帮到你https://github.com/pigrange/buddy_system_allocator

**Comment by kamome1037** [comment]
![``BAMIG_6L3A)2B~}8Y2Y7X](https://user-images.githubusercontent.com/73805584/125928405-67054bbb-1a93-4a9b-bd3f-fed04d82277c.png)
这是调试部分的代码

**Comment by RINNE-TAN** [comment]
![``BAMIG_6L3A)2B~}8Y2Y7X](https://user-images.githubusercontent.com/73805584/125928405-67054bbb-1a93-4a9b-bd3f-fed04d82277c.png)
这是调试部分的代码

**Comment by MorningGloryy** [comment]
![issue](https://user-images.githubusercontent.com/86345383/126131844-c5bb1f62-368c-44d6-9c17-81dfb1d766c4.png)
![issue0](https://user-images.githubusercontent.com/86345383/126131877-1babd5e7-f234-4f60-a606-b7f60c273dab.png)
经过测试最后一次分配的都未回收

**Comment by MorningGloryy** [comment]
![9_XNG~}ZL0T{A)@_5K}PQCP](https://user-images.githubusercontent.com/86345383/126136603-4f0ca6a7-e43b-4700-aabb-2731e7f19fb9.png)
![{BNR4N9I)G1Y6~STUN9)G74](https://user-images.githubusercontent.com/86345383/126136601-7bd0f41b-0f9f-44c4-ad57-a9bf2b8a923c.png)
![5LRX5K((8@EDQ`N1PEYJ7EB](https://user-images.githubusercontent.com/86345383/126136602-f332a2b8-a3dd-4f6d-9c55-d92cdeb3c6be.png)
主函数，测试和输出代码

**Comment by kamome1037** [comment]
了解了，这两种行为上应该是一样的，应该是我的测试代码中后面有一部分把vec的空间释放了
```rust
for (i, value) in vec.into_iter().enumerate() {
        assert_eq!(value, i);
    }
    println!("heap test passed");
```
我当时忽略掉了这个行为
