### ISSUE TITLE
println 死锁问题

### ISSUE THREAD

**Issue by Shuumatsu** [rcore-os/rCore-Tutorial#148]
![image](https://user-images.githubusercontent.com/15049134/125985775-692b7819-6e92-40d3-b668-f739d71ce5ac.png)

我现在的设计是把Stdout包在一个Mutex里面 这样的话可以保证多核的情况下每个核的输出不会混在一起

但是如果在 print 的途中发生了中断，而中断处理函数内调用了 print 的话就会造成死锁

请问一个合理的设计应该是怎么样，希望有人能告诉我怎么解决这个问题。谢谢。

**Comment by wyfcyx** [comment]
在获取到锁之后，可以首先将`sstatus.sie`置0屏蔽掉所有同特权级中断，然后进行输出操作，之后将上述标志位还原使能中断，最后再释放锁。这样相当于构造了一段使得当前处理核不会进入中断的执行区间，在此区间内的操作不会受到中断影响。这种做法在单核和多核环境下均起作用。

**Comment by Shuumatsu** [comment]
请问屏蔽中断的话，那这期间发生的中断会丢失吗，这样我们漏掉了一些中断处理会不会造成一些问题

**Comment by wyfcyx** [comment]
首先我们需要尽量保证屏蔽中断的区间尽量短，即仅在必要时才屏蔽中断，这样可以减少中断丢失的风险。其次，有些中断丢失了也没有问题，因为中断的发送者发现你没有处理的话，下一次中断还会包括上次中断的信息（如virtio）。另外，某些情况下屏蔽中断中断也不会丢失，它可能会被硬件缓存下来，等到开中断之后再触发。

**Comment by Shuumatsu** [comment]
感谢讲解 我把代码改成下面这样后本来会出现死锁的地方确实不再死锁了

![image](https://user-images.githubusercontent.com/15049134/126029120-25bb4059-a0b4-488e-aa6d-2c8fd2d4caad.png)
![image](https://user-images.githubusercontent.com/15049134/126029121-9f985bc8-7d93-44b8-a782-bd3ca8da4c8d.png)

然后我意识到一个问题是，因为代码上看不出来 `f()` 依赖前后的关于 sie 的设置，会不会在某些时候 出现这样的可能
        因为编译器 reorder 等原因，使得 `f()` 在 `set_sie` 和 `clear_sie` 围成的临界区外执行了

在 Rust 中该怎么保证执行的顺序呢

**Comment by wyfcyx** [comment]
像这种函数调用的情况应该不会出现reorder的，如果实在不放心的话可以加一个[compiler fence](https://doc.rust-lang.org/core/sync/atomic/fn.compiler_fence.html)。

**Comment by Shuumatsu** [comment]
谢谢讲解
