### ISSUE TITLE
关于与之前版本不同的线程切换过程

### ISSUE THREAD

**Issue by Tuyixiang** [rcore-os/rCore-Tutorial#17]
@jiegec @wyfcyx @wangrunji0408 @LyricZhao @xy-plus 

之前在重构教程时，本着简洁性的目的，在抄 V2 教程时修改了线程切换的过程，现在看会对内核结构有一定影响。这里说明一下情况，询问大家意见。

- 旧方法（V2）
  - 中断时保存 Trap Frame，然后用一个类似于协程 yield 的方式保存上下文并切换到 idle thread。之后 idle 进行线程调度并上下文切换到另一个线程，这个线程再执行原先 yield 之后的内容，即 restore Trap Frame。
  - 中断时，用户线程各自设有内核栈，内核线程直接使用自己的栈
- 新方法（V3）
  - 中断时保存 Trap Frame，在中断处理中直接进行线程调度，然后加载另一个线程的 Trap Frame。
  - 中断时，所有用户线程公用一个内核栈（因为不会在一个用户线程中断处理完成前启动另一个用户线程），内核线程使用自己的栈

一个显著的区别在于，V2 中会有内核线程来处理调度，而 V3 中则没有（在教程最后状态，不运行任何内核线程）。

如果要在 V3 的系统上继续开发，我认为可能会涉及更多在中断时进行的任务（比如系统调用），而不怎么会用到内核线程。内核线程如果需要进行一些高权限操作，可能需要进行系统调用或者暂时关闭中断。

不过我不清楚在多核上会出现什么情况？zCore（我只粗略看了一下）好像统一了 Trap Frame 和 Context，但是切换线程还是要分两层来切换，这样做是不是有什么优势我没有注意到（比如之后实现 async）？

> **关于以前提到过的内核线程 bug**
>
> 目前的代码存在一个小 bug（但不难解决），即一个内核线程在中断调度的时候，把 Trap Frame 放在了线程自己的栈上，此时如果切换其他线程会先切换页表，然后找不到栈 PageFault。  
> （如果是用户线程发生中断，中断处理就会用公用的内核栈，它是在所有线程页表中的，所以不会有问题）
> 
> 它的解决思路其实很简单，就是让内核线程也使用公用的内核栈。（如果大家觉得以 V3 的新思路进行下去没有问题我就这么修）

**Comment by wangrunji0408** [comment]
正好我也想讨论一下是否可以引入 zCore（和目前 @jiegec 重构后的 rCore）新的处理方式：

主要是彻底分离了 **多线程** 和 **用户态** 这两个概念。

* 多线程：可以理解为内核中的 `std::thread`，对外只暴露两个 API
  * `spawn(|| {...})`：传入一个函数创建新线程
  * `executor::run()`：运行所有就绪线程

* 用户态：对外 API 是一个阻塞函数调用，类似用户程序执行系统调用进入内核
  * `context.run()`：这里的 `context` 类似于 `TrapFrame`，保存了用户态的所有寄存器状态。调用此函数即恢复寄存器并进入用户态，当下一次陷入内核时保存新的寄存器状态，并且函数返回继续执行。

这是两件完全正交的事情，也就是说：

* 可以没有多线程，直接在 main 函数里 `context.run()` 执行用户程序
* 也可以没有用户态，内核本身就是一个传统意义上的多线程程序

而当二者结合起来使用，画风是这样的：
```rust
let thread = Thread::new(...);                   // 创建新的用户线程对象
thread::spawn(move || {                          // 创建一个新内核线程来运行它，这里将 thread 对象 move 到了新线程中
    loop {
        let mut context = thread.get_context();  // 获取此用户线程的寄存器状态
        context.run();                           // 进入用户态执行，直到某种原因陷入内核返回
        let exit = match context.trap_num {      // 查看回到内核的原因，分别处理，最后告诉我是不是结束了
            SYSCALL => syscall(&mut context),    // 执行系统调用
            TIMER => thread::yield_now(),        // 让出 CPU，切换到其它线程
            PAGE_FAULT => {...}
        };
        thread.put_context(context);             // 不运行的时候 context 还回去，因为可能其它人要进行修改（以实现 debugger）
        if exit { break; }                       // 线程执行完毕退出？否则循环
    }
    // 函数执行完毕，内核线程即将销毁
});
```

这样的好处是，我们可以用不同的库分别处理好各自的工作：

* 多线程：[std::thread](https://doc.rust-lang.org/nightly/std/thread/index.html)，[async-std::task](https://docs.rs/async-std/1.6.2/async_std/task/index.html)，[executor](https://github.com/rcore-os/executor)
* 用户态：[trapframe-rs](https://github.com/rcore-os/trapframe-rs)

并且统一了线程与协程，内核态OS与用户态libOS的代码接口：

* `std::thread::spawn` 线程 <-> `async_std::task::spawn` 协程
* `context.run()` 通过 iret-int 切换特权级 <-> `context.run_fncall()` 通过 ret-call 保持特权级

还有就是 async 的需要，这涉及到对函数调用风格和内核栈的处理：

* 传统方法是 **用户调用内核** 的风格：线程的主体在用户态，偶尔调用内核的服务函数
* zCore 方法是 **内核调用用户** 的风格：线程的主体在内核态，每次去用户态跑一段时间，回来就处理一下

从内核栈的使用来看：
* 传统方法在用户态执行时内核栈是清空的，进入内核后从栈顶开始用，只能从全局变量获取上下文
* zCore 方法在用户态执行时内核栈是保留的，回到内核后从离开的位置继续用，可以用局部变量保存上下文

因此：
* 传统方法必须用类似全局 thread-local 变量的方式保存当前线程上下文（如 `Processor::current_thread()`），而上面的代码中直接就用局部变量，配合从闭包外 move 进来也很自然，也更好管理生命周期。
* 如果改成协程：由于 Rust 是无栈协程，所有协程在执行时共用一个栈，栈的最上面还有上层函数的上下文信息。因此**进入用户态就清空内核栈的传统方法是行不通的**，才有了 zCore 现在的做法。

从内核函数调用的视角来看：
* zCore 方法线程的函数调用生命周期是完整的，栈上内容一定会被回收。
* 传统方法线程的函数调用栈是割裂的：首先需要构造一个函数返回来进入用户态，并且最后一次回内核 yield 函数永远不会返回。
  **这种做法与高级语言的函数风格相悖，并由此带来一个很大的资源泄漏问题**：最后这次 yield 发生时函数栈上所有的对象都永远不会 drop。

正是出于以上考虑，我认为传统方法是 C 时代的产物，不再适合 Rust 所有权以及协程的需求，因此就在 zCore 中改掉了。
也在此征求大家的意见：要不要把 Tutorial 也改成这样？如果改的话感觉是个大工程，代码和文档都要大改。

**Comment by Tuyixiang** [comment]
@wangrunji0408 这个思路确实十分巧妙，而且我觉得对于学生理解起来也不难。

另外我有一个问题：如果几个组件通过调库来解决，我们的 Tutorial 是不是就缺少了一些教学的内容？我觉得作为 OS 的教程，至少线程的 spawn 和 execute 一定是需要代码和仔细讲解的。

**Comment by wangrunji0408** [comment]
> @wangrunji0408 这个思路确实十分巧妙，而且我觉得对于学生理解起来也不难。
> 
> 另外我有一个问题：如果几个组件通过调库来解决，我们的 Tutorial 是不是就缺少了一些教学的内容？我觉得作为 OS 的教程，至少线程的 spawn 和 execute 一定是需要代码和仔细讲解的。

我觉得这些还在教程的范围内，应该让读者自己实现这两个库的。

**Comment by Tuyixiang** [comment]
我想到一种在目前框架上的修改方案，修改的量会少一些，但是没法把协程统一进来。（我其实也不太清楚 zCore 里面的协程是怎么使用的。）

修改后大概是以下流程：

```rust
// 内核初始化之后进入这个流程
loop {
  // 这里进行线程调度
  let thread = thread_pool.get_next();
  // 执行用户线程直到发生中断
  thread.run();
  // 根据情况进行处理
  match thread.context.code {
    TIMER => ...,
    SYSCALL => ...,
    ...
  }
  // 将线程放回线程池（thread 中会标记它是否结束/进入等待，调度器相应处理）
  thread_pool.update(thread);
}
```

**Comment by Tuyixiang** [comment]
另外我们的内核中会不会发生嵌套异常？目前我们是选择简化许多实现（比如说内核映射常驻页表）来避免类似的复杂情况。也不太清楚如果放到多核上执行会有什么其他需要考虑的东西。

**Comment by wangrunji0408** [comment]
出于简单考虑可以不支持嵌套异常。不过 trapframe-rs 库还是实现了内核态中断/异常的处理：和传统方法一样在当前栈上保存中断帧，进入一个中断处理函数。目前只是简单地 panic 打印中断帧，以方便调试。

如果是多核的话，要么中断时继续用原来的栈（V2），要么每个核有自己独立的中断栈（V3）。暂时想到这些。

**Comment by LyricZhao** [comment]
我也比较同意新的更优雅的做法（虽然就教学上可能太不传统会激进一些）。如果要对代码和文档进行修改的话，我可以接受。另外，我们需要在实现的时候尽量少引入第三方库。

**Comment by wyfcyx** [comment]
认同新的做法更加优雅、也更加 Rust，但是由于可能与目前的教学内容有不小的差别，可能还需要跟陈老师、向老师协调一下是在这一版中实装，还是在更加贴近 zCore 的下一版中再进行改进。

**Comment by chyyuu** [comment]
实验与教学相辅相成。
做为实验类的教程，我觉得用新的方法更好。
不过个人建议把这做为v4版本的内容。v3版本主要是完善/fix一些小一点的内容。
如果2021春季OS课前，我们的v4版本（SMP+k210+上面的内容）的教程出版了或者稳定了，明年春季的课程内容会相应调整。

@xyongcn 向老师意见？

**Comment by xyongcn** [comment]
我也更喜欢基于异步机制来完全重新设计操作系统。此前我与陈老师交流过此事，但我可能更激进一些，希望提高用户态代码的地位，利用异步的系统调用来减少，用户态代码过于频繁地回到内核态。我想像的一个场景是，有两个核的系统中，一个核跑用户态代码，另一个核上跑内核，这里两边都能十分高效。
一个可能麻烦是，中断响应的时效性如何？我没有想明白。这里需要异步和实时性之间的折中。这个问题好像无法绕开。
建议安排能有一次专门的讨论，把新方法下的基本概念讨论明白。

**Comment by luojia65** [comment]
提出一个改进：中断里切换上下文，如果切换就往sscratch里写东西，不切换就不写。
因为进入中断后，sscratch的内容是中断前上下文的描述（比如说sp的值）。如果不修改，后面的汇编代码直接读取sscratch，就作为还原到上一个上下文。如果修改（在中断处理代码里修改sscratch），就说明要切换到新的上下文，后面的汇编代码会读取到新的上下文里面。
这样就不用把新的sp作为返回值了。然后，运行时的库或者操作系统可以提供方便的函数，用于在rust代码里修改sscratch。

尝试给出一个伪代码。这里把上一个上下文的sp标注为sp_0，中断处理器的标注为sp_1，下一个上下文标注为sp_2。
```assemble
_start_trap:
sd      ..., ...(sp_0) # 保存到原上下文的栈
addi    sp_0, sp_0, ... # 正数
csrrw   sp_1, sscratch, sp_0

csrr    a0, sscratch    # 第一个参数 a0 <- sp_0
call    rust_handler
# Rust编译handler，将会保存临时变量到sp_1的栈上
# handler可能会修改sscratch的值为sp_2

csrrw   sp_2, sscratch, sp_1 # 如果不修改，sp_2等于sp_0，相当于不切换
addi    sp_2, sp_2, ... # 负数
ld      ..., ...(sp_2) # 从新上下文的栈弹出

sret
```

**Comment by Tuyixiang** [comment]
@luojia65 

这样做本质上没有很大差异，而我们希望避免在 Rust 代码中直接操作寄存器。

另外，也需要注意的是中断的第一条指令必须是交换 `sscratch` 和 `sp`，因为栈有可能正在缺页。
