### ISSUE TITLE
可否考虑替换在导入包时使用 * 这种用法？转而使用明确的包名称。

### ISSUE THREAD

**Issue by jwnhy** [rcore-os/rCore-Tutorial#19]
这种用法对于教程来说不是特别合适。

使用 `*` 来导入所有包的机制让初学者难以对某个引入的对象进行溯源，而不得不翻找所有的来源。

虽然说本教程并不希望同学们以复制粘贴的方式完成 Lab 。但是在我个人的学习流程中，如果有明确的指引，可以省掉很多无意义的翻找时间和误解引起的浪费，也可以对教程整体的结构有更好的了解。

**Comment by Tuyixiang** [comment]
现代的 Rust IDE（例如 VSCode + rust-analyzer 插件，CLion + Rust 插件）都可以点击函数找到其定义。

因为目前实验架构尚未完全定型，在不断的修改过程中使用具体的 `import` 指令会带来很多无意义的工作量，暂时没有计划替换掉 wildcard。

**Comment by jwnhy** [comment]
啊这点我了解，可能和我自己学习习惯有关系，我一般自己手敲。

写的顺序不对的话IDE经常给我 `use` 一些奇怪的系统库。

那我大概了解了，我看看能不能给教程做一个文件间的依赖关系图，便于理解。
