### ISSUE TITLE
令狐壹冲Rust语言教学视频中出现的错误

### ISSUE THREAD

**Issue by Jacksadventure** [rcore-os/rCore-Tutorial#20]
令狐壹冲Rust语言教学视频中可能会出现错误，为了不误导大家，欢迎有能力的同学在此贴分享你发现的错误，感谢！

**Comment by dingiso** [comment]
准确来说，Rust规定  存放在栈上的数据是长度固定的 放过来是错误的，例如 rust 中的Box<T>类型可以显式的在堆上分配内存 
```Rust
let x = Box::new(5) 
```
- x分配在栈上，值5分配在堆上，其地址存在x的栈中；
- 当函数结束,值5所在的堆空间先被释放，接着自己所在的栈空间释放
