### ISSUE TITLE
QEMU 5.0.0 中无法进行外设中断（键盘）

### ISSUE THREAD

**Issue by Tuyixiang** [rcore-os/rCore-Tutorial#3]
使用 QEMU 5.0.0 版本的话，外设中断似乎不会触发中断。（4.2.1 可以工作）

猜测和这几个祖传 magic number 有关？

```rust
// 在 OpenSBI 中开启外部中断
*PhysicalAddress(0x0c00_2080).deref_kernel() = 1 << 10;
// 在 OpenSBI 中开启串口
*PhysicalAddress(0x1000_0004).deref_kernel() = 0x0bu8;
*PhysicalAddress(0x1000_0001).deref_kernel() = 0x01u8;
```

@wangrunji0408 @jiegec

**Comment by jiegec** [comment]
第一行是配置 plic，后两行是配置 uart 16550。

相关代码：https://github.com/rcore-os/rCore/blob/69564c55ae48d2ec206cfc2b48ca21c83ddf64eb/kernel/src/arch/riscv/board/virt/mod.rs#L9

可以加上不一样的几行配置。
