### ISSUE TITLE
Rustling 练习缺少 structs3.rs 文件

### ISSUE THREAD

**Issue by Wintersweet0** [rcore-os/rCore-Tutorial#36]
我在rustling的过程中发现\rustlings\exercises\structs文件夹中缺少structs3.rs，不知道这个怎么修复，重装的话会很麻烦...

**Comment by am009** [comment]
我的rustling里就没有structs3.rs
会不会和我之前checkout 3.0.0有关系

**Comment by SKTT1Ryze** [comment]
少几个题目文件是正常的，我的版本也是缺少某些题目，应该问题不大

**Comment by yunwei37** [comment]
去看了一下历史，struct3.rs 应该是3.0.0之后才加进去的（重装或者只下载一个文件可能解决不了问题，如果需要的话也许可以考虑直接clone最新版本）

**Comment by dingiso** [comment]
访问这个网站，你可以下载github仓库中的一部分内容以弥补你缺失文件
[Downgit](http://zhoudaxiaa.gitee.io/downgit/#/home)
比如你可以copy 这个网址 https://github.com/rust-lang/rustlings/blob/main/exercises/structs/structs3.rs 并下载这个文件
