### ISSUE TITLE
关于所有权问题的一些理解，欢迎大家指正。

### ISSUE THREAD

**Issue by xushanpu123** [rcore-os/rCore-Tutorial#37]
rust函数中临时申请的数据要么存放在堆中要么存放在栈中，诸如i32,u32,&str等数据存放在栈中，因为他们自身容量较小，且size固定。而另一类可变size的数据，如Vec，String等类型的数据，由于其大小不固定，时刻需要因为长度变化而由操作系统重新分配内存，所以具体信息存放在堆中，只在栈中存储起始指针，长度的“胖指针”。当堆中数据需要被函数调用或者被赋值的时候，由于直接clone堆中信息代价太大，rust倾向于让新变量指向原本存储信息的地址，然而rust本身是一种变量离开作用域便会自动free的语言，两个指向同一个地址的指针会造成内存不安全，因此赋值或者函数调用会造成堆上变量的所有权转移。解决方式有两种，第一种，采用深度复制的方法，使得新获取的变量虽然与原变量内容相同，但是其实是指向其他地址的一个copy。另一种方式，利用&符号来进行借用，表示新变量只是借用了原变量的所有权，并无权释放，而一个变量无论是出借了value所有权还是本身所有权就是从别处借来的，他都无法再向别人出借所有权。不知自己对这块的理解是否有所偏差，欢迎指正！

**Comment by yunwei37** [comment]
感觉这一句话似乎有一点偏差？

> 而一个变量无论是出借了value所有权还是本身所有权就是从别处借来的，他都无法再向别人出借所有权。

一个变量本身是引用，它好像也还可以把引用传递给别的引用变量？

**Comment by xushanpu123** [comment]
额，我试一下。



---原始邮件---
发件人: "云微"<notifications@github.com&gt;
发送时间: 2020年7月7日(周二) 晚上9:09
收件人: "rcore-os/rCore-Tutorial"<rCore-Tutorial@noreply.github.com&gt;;
抄送: "xushanpu123"<798304030@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [rcore-os/rCore-Tutorial] 关于所有权问题的一些理解，欢迎大家指正。 (#37)




 
感觉这一句话似乎有一点偏差？
  
而一个变量无论是出借了value所有权还是本身所有权就是从别处借来的，他都无法再向别人出借所有权。
  
一个变量本身是引用，它好像也还可以把引用传递给别的引用变量？

**Comment by yunwei37** [comment]
```rs

fn main() {
    let x = 1;
    let y:&i32 = &x;
    let z:&i32 = y;
    println!("{}",x);
    println!("{}",y);
    println!("{}",z);
}
```
这样？

**Comment by xushanpu123** [comment]
i32类型不在我们考虑范围内啊，是存在栈上的数据。



---原始邮件---
发件人: "云微"<notifications@github.com&gt;
发送时间: 2020年7月7日(周二) 晚上9:16
收件人: "rcore-os/rCore-Tutorial"<rCore-Tutorial@noreply.github.com&gt;;
抄送: "xushanpu123"<798304030@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [rcore-os/rCore-Tutorial] 关于所有权问题的一些理解，欢迎大家指正。 (#37)




  fn main() {     let x = 1;     let y:&amp;i32 = &amp;x;     let z:&amp;i32 = y;     println!("{}",x);     println!("{}",y);     println!("{}",z); }

**Comment by yunwei37** [comment]
```
fn main() {
    let x = String::from("Hello");
    let y:&String = &x;
    let z:&String = y;
    println!("{}",x);
    println!("{}",y);
    println!("{}",z);
}
```
抱歉，可能是我阅读不够仔细；如果是指在堆上分配的话，应该用String这样

**Comment by xushanpu123** [comment]
能跑吗？能跑的话应该就是我说的有误。



---原始邮件---
发件人: "云微"<notifications@github.com&gt;
发送时间: 2020年7月7日(周二) 晚上9:23
收件人: "rcore-os/rCore-Tutorial"<rCore-Tutorial@noreply.github.com&gt;;
抄送: "xushanpu123"<798304030@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [rcore-os/rCore-Tutorial] 关于所有权问题的一些理解，欢迎大家指正。 (#37)




 fn main() {     let x = String::from("Hello");     let y:&amp;String = &amp;x;     let z:&amp;String = y;     println!("{}",x);     println!("{}",y);     println!("{}",z); }  
这样呢...

**Comment by dingiso** [comment]
有点乱，其实ownership只有三个规则

1. Rust 中的每一个值都有一个被称为其 所有者（owner）的变量。
2. 值在任一时刻有且只有一个所有者。
3. 当所有者（变量）离开作用域，这个值将被丢弃。

和几个相关知识 ： **变量作用域，借用 ，可变借用**

你可以好好读一下这两篇文章，相信你能得到更多，更全面的内容
[Rust之ownership](https://www.jianshu.com/p/d732609d3b1e)
[什么是所有权](https://kaisery.github.io/trpl-zh-cn/ch04-01-what-is-ownership.html)

准确来说，Rust规定  存放在栈上的数据是长度固定的 放过来是错误的，例如 rust 中的Box<T>类型可以显式的在堆上分配内存 
```Rust
let x = Box::new(5) 
```
- x分配在栈上，值5分配在堆上，其地址存在x的栈中；
- 当函数结束,值5所在的堆空间先被释放，接着自己所在的栈空间释放
