### ISSUE TITLE
如何构建一个全局的HashMap

### ISSUE THREAD

**Issue by xushanpu123** [rcore-os/rCore-Tutorial#38]
rust语言任何变量定义的时候都需要赋值，但是HashMap::new()不能在全局变量申请时调用，那么如何构建一个全局的HashMap呢？

**Comment by dingiso** [comment]
### 回答
我们常用 lazy_static crate 创建全局变量同样适用于 hashmap 。 
如果想创建一个 可变的hashmap 则需要借用 cell  或 mutex 以提供内部可变性


```Rust
#[macro_use]
extern crate lazy_static;

use std::collections::HashMap;
use std::sync::Mutex;

lazy_static! {
    static ref MutMap: Mutex<HashMap<i32, String>> = Mutex::new(HashMap::new());
    static ref Map: HashMap<i32, String> = {
        let mut map = HashMap::new();
        map.insert(18, "hury".to_owned());
        map
    };
}

fn MapInsert() {
    MutMap.lock().unwrap().insert(1, String::from("aaa"));
}

fn main() {
    MapInsert();
    println!("{:?}", *MutMap);
    println!("{:?}", *Map);
}
```
### 解释
1. lazy-static crate 可以取代一些创建单例的复杂代码
2. Rust中的可变或不可变主要是针对一个变量绑定而言的。对于类型而言，Rust标准库中的std::cell模块（Cell, RefCell等），提供内部可变性的容器，弥补了Rust所有权机制在灵活性上和某些场景下的不足。
通常情况下，共享不可变，可变不共享。

- 内部可变性，单线程使用Cell <T>和RefCell <T>。
- 内部可变性，多线程使用Mutex<T>，RwLock<T>
### 借鉴
[Rust中的全局静态变量](https://segmentfault.com/a/1190000019897166)
[如何理解Rust中的可变与不可变](https://rustcc.cn/article?id=37d1cb4f-5cc9-4adc-b41a-dbe4914bf4b5)
