### ISSUE TITLE
如何用iter和range实现阶乘

### ISSUE THREAD

**Issue by gystar** [rcore-os/rCore-Tutorial#43]
pub fn factorial(num: u64) -> u64 {
    // Complete this function to return the factorial of num
    // Do not use:
    // - return
    // Try not to use:
    // - imperative style loops (for, while)
    // - additional variables
    // For an extra challenge, don't use:
    // - recursion
    // Execute `rustlings hint iterators4` for hints.    
}
要求在注释上面，不用递归、多余的变量

**Comment by yukiiiteru** [comment]
map-reduce，rust-by-example有提及到，用`fold`方法

**Comment by shiweiwww** [comment]
let result = (1..nums).fold(nums, |acc, x| acc*x);

**Comment by wyfcyx** [comment]
有一个更简洁但不太通用的
```Rust
(1..=num).product()
```

**Comment by yunwei37** [comment]
放一个自己的：
```rs
pub fn factorial(num: u64) -> u64 {
    (1..num).fold(1, |acc, x| acc * x) * num
}
```

**Comment by gystar** [comment]
谢谢。
