### ISSUE TITLE
关于Lab1实验指导中时钟中断部分某些措辞使用的疑问

### ISSUE THREAD

**Issue by SKTT1Ryze** [rcore-os/rCore-Tutorial#47]
### Lab1实验指导中时钟中断部分某些措辞使用的疑问
在Lab1实验指导时钟中断部分：[timer-interrupt](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-1/guide/part-6.html)中  
下面的阐述：  

> 这里可能引起误解的是 sstatus::set_sie()，它的作用是开启 sstatus 寄存器中的 SIE 位，与 sie 寄存器无关。SIE 位决定中断是否能够打断 supervisor 线程。在这里我们需要允许时钟中断打断 内核态线程，因此置 SIE 位为 1。
另外，无论 SIE 位为什么值，中断都可以打断用户态的线程。

对于其中的`线程`一词，是不是改为`进程`更为恰当？  
下面是对于时钟中断的一个概念说明：  
> 时钟中断是系统中调度和抢占的驱动因素，在时钟中断中会进行进程运行时间的更新等，并更新调度标志，以决定是否进行调度。  

下面是知乎上关于线程和进程区别的讨论：[discussion](https://www.zhihu.com/question/25532384/answer/131906596)  
我觉得在操作系统内部层面`进程`这个概念会比较合适。  
欢迎同学们参与讨论。

**Comment by yunwei37** [comment]
一般来说，线程是CPU进行调度的基本单位，而进程更多侧重的是资源分配；在时钟中断的时候进行线程的调度。因此这边用线程应该并没有问题？

**Comment by LyricZhao** [comment]
感谢你的提问，我完全同意 @yunwei37 的说法，中断切换的是线程，是时间上调度的单位；进程是资源分配的单位，比如一个进程可以有多个线程，这些线程会在时间上被 OS 的调度机制来调度，这些线程共享同一个虚拟内存空间（所谓的进程的资源），这个空间是独立于其他进程的。

在第一章有疑问很正常，读完后面的章节，你会对这两个概念在 OS 下的解释有深刻的认识。
