### ISSUE TITLE
环境部署的文档建议

### ISSUE THREAD

**Issue by dingiso** [rcore-os/rCore-Tutorial#48]
### qemu
linux 中 qemu 安装 使用中，指令安装的qemu 可能不是我们使用的qemu，准确化后的指令安装会更加清楚
```bash
# Ubuntu / Debian / Windows WSL
sudo apt-get install qemu-system-riscv64

# CentOS / Fedora / RedHat / SUSE
sudo yum install qemu-system-riscv64
```
### 安装rust工具链

下面的命令 以失效， ustc 不再提供rust-static的镜像
```bash
export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup
curl https://sh.rustup.rs -sSf | sh
```
 **改正：**
如果 官方文档的方式无法使用，或停滞在
```bash
info: downloading installer
```

可通过以下官方网站 选择合适的版本进行自行下载
[Rust官方下载](https://forge.rust-lang.org/infra/other-installation-methods.html)  
一般选择此[x86_64-unknown-linux-gnu](https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init)版本进行下载即可。

**Comment by Tuyixiang** [comment]
感谢指出。我看到各种包管理器都没有提供 `qemu-system-riscv64`，那一段就不展开讲了，推荐自行编译源码。

中科大 Rust 源好像还可以访问，`RUSTUP_DIST_SERVER` 已经换成清华，`RUSTUP_UPDATE_ROOT` 似乎找不到其他哪里提供。

**Comment by LyricZhao** [comment]
只要在 Ubuntu 等系统上的**源比较新**，安装 QEMU 是会包含 qemu-system-riscv64 工具的，QEMU 在这个意义上是一个工具集，所以我在文档中的描述是“如果源中包含的 QEMU 版本比较新，则可以用 `apt-get install qemu` 来安装”，qemu-system-riscv64 只是这个工具集中的一个，可能很多源没有单独放出来一个该工具，所以我个人觉得第一条不太需要修改。

**Comment by Tuyixiang** [comment]
> 只要在 Ubuntu 等系统上的**源比较新**，安装 QEMU 是会包含 qemu-system-riscv64 工具的，QEMU 在这个意义上是一个工具集，所以我在文档中的描述是“如果源中包含的 QEMU 版本比较新，则可以用 `apt-get install qemu` 来安装”，qemu-system-riscv64 只是这个工具集中的一个，可能很多源没有单独放出来一个该工具，所以我个人觉得第一条不太需要修改。

直接安装 `apt-get install qemu` 会包含所有的平台吗

**Comment by LyricZhao** [comment]
会包含该源的版本的全部平台吧。
