### ISSUE TITLE
函数的生命周期推断

### ISSUE THREAD

**Issue by Lincyaw** [rcore-os/rCore-Tutorial#49]
问题1: rust中只要定义了传入或者传出变量是引用的, 就会报错吗
以下函数定义之后没有被调用就报错了
```rust
fn longer(s1: &str, s2: &str) -> &str {
    if s2.len() > s1.len() {
        s2
    } else {
        s1
    }
}
```
本来以为在调用该函数的时候会报错, 但是实际上是定义了函数之后就报错了
![image](https://user-images.githubusercontent.com/53161583/87019176-de181780-c204-11ea-927d-ae73c079ba6c.png)

问题2:
该代码是能够正常运行的, 而在教程中是说 它的实际含义是 longest 函数返回的引用的生命周期与传入该函数的引用的生命周期的较小者一致。就不应该编译成功
```rust
fn longer<'a>(s1: &'a str, s2: &'a str) -> &'a str {
    if s2.len() > s1.len() {
        s2
    } else {
        s1
    }
}

#[test]
fn lifetime(){
    let r;
    let s1 = "rust";
    {
        let s2 = "ecmascript";
        r = longer(s1, s2);
    }
    println!("{} is longer", r);
}
```
教程中给的例子也表明这是无法成功的
![image](https://user-images.githubusercontent.com/53161583/87020877-0f91e280-c207-11ea-81f8-62e44efe77e4.png)

可这为啥成功了呢???

**Comment by Lincyaw** [comment]
试了一下完全和教程一样的代码, 是会报错的。 然后就怀疑是类型的问题。
在使用&str的时候， 是像我说的那样的现象， 使用String::from的时候就会报错. 是什么原因呢? 是一个在堆上, 一个在栈中的原因吗

**Comment by dingiso** [comment]
### 问题1
不是的，出现问题是因为当出现多个 引用 和 借用时 编译器是在编译时候检查，无法推断返回值的Lifetime应该是比  `x` 长，还是比 `y` 长 ， 单个时不会出现问题。
```rust
fn foo(x: &str) -> &str {
    x
}
```
因为实际上，编译器自动推导了生命周期，相当于：
```rust
fn foo<'a>(x: &'a str) -> &'a str {
    x
}
```

### 数学证明：
推导公式： 当输出值R依赖输入值X Y Z ...，当且仅当输出值的Lifetime为所有输入值的Lifetime交集的子集时，生命周期合法。
    `Lifetime(R) ⊆ ( Lifetime(X) ∩ Lifetime(Y) ∩ Lifetime(Z) ∩ Lifetime(...) )`
对于问题1：
因为返回值同时依赖输入参数x和y，所以
    `Lifetime(返回值) ⊆ ( Lifetime(x) ∩ Lifetime(y) )
    即：
    'a ⊆ ('a ∩ 'a)  // 成立`

### 问题二
问题二 是因为 `“ecmascript”` 这种类型如果显式来写的的类型是  `&'static str` , 其生命周期是整个程序的运行周期。在编译器进行推算的时候不会出现问题。

**简单来说**， 虽然 `string2` 不存在了，但是其存在的内部值依然存在，编译器进行判断回通过，而图片中的例子，`string`类型随着作用域的完成会消失，其内部值也会消失，编译器无法通过.

### 借鉴
[Rust生命周期](https://wiki.jikexueyuan.com/project/rust-primer/ownership-system/lifetime.html)

> 上面这篇文章能帮你完全理解 生命周期 的内容，推荐进行阅读

**Comment by am009** [comment]
update: https://www.zhihu.com/question/48196609
https://zhuanlan.zhihu.com/p/93846179
https://zhuanlan.zhihu.com/p/93193353
https://medium.com/nearprotocol/understanding-rust-lifetimes-e813bcd405fa
看完这几篇文章发现，是我还不理解生命周期

----------

我想到了下面这几种生命周期的写法
```rust
fn the_longest1 <'a>(s1 : &'a String , s2 : &'a String ) -> &'a String {
    if s1.len() > s2.len() { s1 } else { s2 }
}
fn the_longest2 <'a, 'b: 'a>(s1 : &'a String , s2 : &'b String ) -> &'a String {
    if s1.len () > s2.len() { s1 } else { s2 }
}
fn the_longest3 <'a: 'c, 'b: 'c, 'c>(s1 : &'a String , s2 : &'b String ) -> &'c String {
    if s1.len () > s2.len() { s1 } else { s2 }
}
fn the_longest4 <'a, 'b>(s1 : &'a String , s2 : &'b String ) -> &'b String {
    s2
}
```
第四种写法，指明了输出的生命周期就是第二个参数的生命周期，这个确实没什么问题。下面这个可以正常运行
```rust
fn main() {
    let c;
    let a = String::from("sdfdag");
    {
        let b = String::from("erv");
        c = the_longest4(&b, &a);
    }
    println!("{}", c);
}
```
这时如果把the_longest4中'a的生命周期标记标成长于'b，也就是改成
```rust
fn the_longest4 <'a: 'b, 'b>(s1 : &'a String , s2 : &'b String ) -> &'b String {
    s2
}
```
再运行也确实会报错，如下：
```
error[E0597]: `b` does not live long enough
  --> D:\rcore_os\hardways\17database.rs:60:26
   |
60 |         c = the_longest4(&b, &a);
   |                          ^^ borrowed value does not live long enough
61 |     }
   |     - `b` dropped here while still borrowed
62 |     println!("{}", c);
   |                    - borrow later used here
```
但是报错说的不是我的函数调用不满足第一个参数的生命周期长于第二个参数？

----------------------
第一种写法，虽然默认规则是输出的生命周期是输入的交集, 但是输入输出全部都标'a, 感觉意思不明确。所以我感觉第三种写法最好，说明输出的生命周期短于a又短于b
第二种写法，似乎调用时第二个参数的生命周期要大于等于第一个参数，但是实际尝试下来并没有相关的检查...
```rust
fn main() {
    let c;
    let a = String::from("sdfdag");
    {
        let b = String::from("erv");
        c = the_longest2(&a, &b);
        println!("{}", c);
    }
}
```
（就算是交换the_longest2的两个参数也不会报错。）
没有相关的检查吗？
另外感觉前三种写法达到的效果都完全相同... 是这样吗？

似乎我没有理解编译器对于生命周期标记的具体的检查机制...

**Comment by luojia65** [comment]
@dingiso 的想法非常好，用一种类似于集合的语言描述，能很快分析出函数的生命周期是否满足要求。我想到一个例子：

```rust
fn choose<'a, 'b>(is_a: bool, a: &'a str, b: &'b str) -> Enum<'a, 'b> {
    if is_a {
        Enum::A(a)
    } else {
        Enum::B(b)
    }
}

#[derive(Debug)]
enum Enum<'a, 'b> {
    A(&'a str),
    B(&'b str)
}
```

这段代码是能过编译的。它的函数的返回值包含两个生命周期，这个可以用类似的描述方法推广开来吗？

**Comment by stellarkey** [comment]
`& str`我一开始也觉得这种常量的生命周期应该贯穿程序。

但是，一个直接定义的字面量和一个通过`to_str()`生成的`&str`的生命周期应该是不同的。

```rust
let s1 = "abc";    // s1是字面量，贯穿始终
{
    let s2 = String::from("abc");
    let s3: &str = s2.to_str();
    // 注意到： s3是借助s2调用函数生成，那么s3的生命周期必然包含在s2之中
}
```

因为函数的返回值如题目中所言是borrow的，所以以上代码的生命周期也能反映问题2的一些性质。

这样问题2应该迎刃而解了。
