### ISSUE TITLE
 关于Iter trait的collect function

### ISSUE THREAD

**Issue by nlxxh** [rcore-os/rCore-Tutorial#52]
### 关于Iter trait的collect function
想问一下，为什么results不同，assert_eq的运行结果会不一样呢

```rust
let results = [Ok(1), Err("nope"), Ok(3), Err("bad")];    
let result: Result<Vec<_>, &str> = results.iter().cloned().collect();    
// gives us the first error  
assert_eq!(Err("nope"), result);  
let results = [Ok(1), Ok(3)];  
let result: Result<Vec<_>, &str> = results.iter().cloned().collect();  
// gives us the list of answers  
assert_eq!(Ok(vec![1, 3]), result);
```

**Comment by chibinz** [comment]
> Result implements FromIter so that a vector of results (Vec<Result<T, E>>) can be turned into a result with a vector (Result<Vec<T>, E>). Once an **Result::Err** is found, the iteration will **terminate**.

From [Rust By Example](https://doc.rust-lang.org/stable/rust-by-example/error/iter_result.html)

**Comment by nlxxh** [comment]
ok，thanks！@chibinz
