### ISSUE TITLE
关于实验一的一些思考

### ISSUE THREAD

**Issue by SKTT1Ryze** [rcore-os/rCore-Tutorial#56]
### 关于实验一的一些思考
在分析 Lab1 的代码过程中，遇到一些问题，其中包括在源码中注释的思考题，和我本人对实验代码提出的一些疑问。希望同学们能指出错误，并且给出建议。  
#### 思考题1
思考：` sscratch `的值最初是在什么地方写入的？  
` sscratch `的作用：  
在核（` hart `）运行用户态代码的时候，` sscratch `用来保存一个指向内核态上下文的指针。在` trap handler `的开始部分，` sscratch `和一个用户寄存器交换值来提供一个`initial working register`。  
因此本人猜测` sscratch `的值最初是开机启动后操作系统运行第一个用户态程序的时候写入的。（不确定）  
#### 思考题2
思考：` a0 `是在哪里被赋值的？（有两种情况）  
+ 在进入函数` handle_interrupt `之前的参数准备阶段被赋值；
+ 从` handle_interrupt `返回时作为返回参数被赋值。
#### 思考题3
思考：为什么不恢复` scause `和` stval `？如果不恢复，为什么之前要保存？  
本人认为` scause `和` stval `不需要恢复，之前也没有保存。  
从这两个寄存器的作用出发思考，` scause `指示发生异常的种类，而` stval `保存了` trap `的附加信息：出错的地址或者非法指令本身。因此这两个寄存器只在中断出现的时候派上用场，在一般情况下不影响程序的运行，而保存上下文的目的就是要保证中断处理完之后回到原来中断的地方程序能继续运行，从这个角度来看就不必保存这两个寄存器。而又回到之前为什么` scause `和` stval `包含在数据结构` Context `中的问题，既然不需要保存，自然就不需要放在` Context `里面了。  
#### 对实验代码的疑问
在恢复上下文过程中，有这样一条指令：  
` os/src/interrupt/interrupt.asm `
```
mv      sp, a0
```
这是从` handle_interrupt ` 中的返回值` a0 `中读取` sp `，而` a0 ` 同时也是作为调用参数传入到` handle_interrupt `中的。  
疑问是：这样的实现方法不是会有风险吗？  
因为后面无论是恢复 CRSs 还是恢复通用寄存器，都与` sp `的值相关，如果返回值不对，或者说在` handle_interrupt `中修改了` a0 `的值，那么后面的恢复上下文过程就无法正确执行，导致系统崩溃。在` x86 `架构中的函数调用机制使用了一种栈帧结构，本人觉得与实验代码的恢复` sp `的机制相比，栈帧结构更为完全。  
另外，在实验代码有这么一行注释：  
```
// 返回的 Context 必须位于内核栈顶
```
也就是说这里返回的指针必须指向内核栈的栈顶。  
这不正反映了这个机制的不稳定性吗。  
欢迎同学们参与讨论。

**Comment by SKTT1Ryze** [comment]
另外补充一点疑问，对于下面代码：  
```Rust
// 在 OpenSBI 中开启外部中断
        *PhysicalAddress(0x0c00_2080).deref_kernel() = 1u32 << 10;
        // 在 OpenSBI 中开启串口
        *PhysicalAddress(0x1000_0004).deref_kernel() = 0x0bu8;
        *PhysicalAddress(0x1000_0001).deref_kernel() = 0x01u8;
        // 其他一些外部中断相关魔数
        *PhysicalAddress(0x0C00_0028).deref_kernel() = 0x07u32;
        *PhysicalAddress(0x0C20_1000).deref_kernel() = 0u32;
```
通过阅读源码，我大概推测这些代码的作用是对特定物理地址映射到的虚拟地址的内存进行赋值，来完成在OpenSBI中开启外部中断的工作。但我不确定，请同学们指正。另外希望同学们指点在OpenSBI中开启外部中断的原理，以及为什么这段代码能实现上述功能。谢谢。

**Comment by yukiiiteru** [comment]
仅针对Lab1做一下回答

### 思考题1

查询RISC-V特权指令手册，未果。查阅OpenSBI的代码，找到了，

在[OpenSBI/lib/sbi/sbi_hart.c](https://github.com/riscv/opensbi/blob/2314101989684585f942b50a827aac4886825ba1/lib/sbi/sbi_hart.c)文件中，`sbi_hart_switch_mode`函数内：

```c
	if (next_mode == PRV_S) {
		csr_write(CSR_STVEC, next_addr);
		csr_write(CSR_SSCRATCH, 0);
		csr_write(CSR_SIE, 0);
		csr_write(CSR_SATP, 0);
	} else if (next_mode == PRV_U) {
		csr_write(CSR_UTVEC, next_addr);
		csr_write(CSR_USCRATCH, 0);
		csr_write(CSR_UIE, 0);
	}
```

再根据函数名即if语句可以得知，在`hart`要切换MODE时，如果要切换到S态，那么将`sscratch`寄存器内写入`0`。

而题目问的是最初，那么最初写入是在bootloader（OpenSBI）加载完毕，即将切换到操作系统内核时，这一特权级切换过程中写入的。

### 思考题2

文件`src/interrupt/interrupt.asm`中，`__interrupt`函数（标记）内，将需要的寄存器值压栈后：

```asm
    # 调用 handle_interrupt，传入参数
    # context: &mut Context
    mv      a0, sp
    # scause: Scause
    csrr    a1, scause
    # stval: usize
    csrr    a2, stval
    jal  handle_interrupt
```

此时（Lab1中），handle_interrupt函数还没有返回值，所以没有第二次写入

### 思考题3

`scause`和`stval`寄存器仅被保存到了`a1`、`a2`寄存器，而这两个寄存器是作为传入参数存在的。

这两个寄存器的值是OpenSBI需要写入的，见[OpenSBI/lib/sbi/sbi_trap.c](https://github.com/riscv/opensbi/blob/1b8c0128f1d79d69ea0a46b758fef4be8dc0a73e/lib/sbi/sbi_trap.c)。操作系统只需要读就可以了。

### 与思考题无关的内容

以上内容均为个人见解，欢迎同学们继续参与讨论

至于后面你说的对于实验代码的疑问，我在Lab1中并没有找到相关代码

经过搜索得知`PhysicalAddress`函数第一次出现是在Lab2，`mv      sp, a0`第一次出现是在Lab4，建议现在先不要看所有Lab完成后总的代码，先看`rCore-Tutorial`的[lab-1分支](https://github.com/rcore-os/rCore-Tutorial/tree/lab-1)的代码即可

另外，第一个思考题是Lab4的，第二个思考题也是Lab4的，第三个思考题没找到

~~说了这么多，其实还是因为是我答不上来~~

**Comment by SKTT1Ryze** [comment]
感谢@wfly1998。思路清晰了许多

**Comment by Tuyixiang** [comment]
很抱歉之前没有说清楚，实验一应当参考实验指导文档和 `lab-1` 分支的代码。你提的这些问题都不是实验一的范畴（第三问是实验框架以前的问题，现已删除）。
master 分支的代码是截止到最后一章完成后的效果，其中还有一些因为迭代而产生的问题，不应该作为实验的参考。

**Comment by SKTT1Ryze** [comment]
感谢@Tuyixiang 指点，我打算做完整个实验再回头思考一下代码，麻烦了。
