### ISSUE TITLE
lab1:part4 文档中汇编代码太长

### ISSUE THREAD

**Issue by chyyuu** [rcore-os/rCore-Tutorial#60]
欢迎提出任何问题

### 涉及文件
docs/lab-1/guide/part-4.md

### 相关段落
文中的代码片段
os/src/interrupt.asm

### 遇到问题
太长了。建议采用asm macro等方式，精简代码；如果不能精简代码，可以精简文档中的代码片段
比如:
```
 SAVE    x3, 3 
 ....
 SAVE    x31, 31
```

**Comment by Tuyixiang** [comment]
有谁知道有什么办法在汇编里面缩减这一段代码吗？文档里可以直接省略号。

**Comment by luojia65** [comment]
前几天看到一系列写操作系统的文章，是Stephen Marz的：http://osblog.stephenmarz.com/ch4.html
“Looking at the Assembly Trap Vector”这一节，他这么做的：

```rust
.set 	i, 1
.rept	30
	save_gp	%i
	.set	i, i+1
.endr
```

**Comment by chibinz** [comment]
目前做到lab1，按照洛佳同学@luojia65提出的方法试了试，发现是可行的。
```RISC-V
# Essential for substitution %i
.altmacro

# length of general purpose registers in bytes
.set reg_size, 8
# No. of registers inside a context frame
.set context_size, 34

# Load register relative to sp
.macro load reg, offset
    ld  \reg, \offset * reg_size(sp)
.endm

.macro load_gp n
    load    x\n, \n
.endm

...

.global __restore
__restore:
    # Restore csr registers
    load    t0, 32
    load    t1, 33
    csrw    sstatus, t0
    csrw    sepc, t1

    .set i, 3
    .rept 29
        load_gp %i
        .set i, i + 1
    .endr

    # Restore ra and sp last
    load    x1, 1
    load    x2, 2

    # Return to the address stored in sepc
    sret
```

rCore-Tutorial master分支上面好像还有跟sscratch内核栈相关的汇编。学长如果觉得ok的话，我可以做一些修改，稍后提交pr。

**Comment by Tuyixiang** [comment]
> 目前做到lab1，按照洛佳同学@luojia65提出的方法试了试，发现是可行的。
> 
> ```
> # Essential for substitution %i
> .altmacro
> 
> # length of general purpose registers in bytes
> .set reg_size, 8
> # No. of registers inside a context frame
> .set context_size, 34
> 
> # Load register relative to sp
> .macro load reg, offset
>     ld  \reg, \offset * reg_size(sp)
> .endm
> 
> .macro load_gp n
>     load    x\n, \n
> .endm
> 
> ...
> 
> .global __restore
> __restore:
>     # Restore csr registers
>     load    t0, 32
>     load    t1, 33
>     csrw    sstatus, t0
>     csrw    sepc, t1
> 
>     .set i, 3
>     .rept 29
>         load_gp %i
>         .set i, i + 1
>     .endr
> 
>     # Restore ra and sp last
>     load    x1, 1
>     load    x2, 2
> 
>     # Return to the address stored in sepc
>     sret
> ```
> 
> rCore-Tutorial master分支上面好像还有跟sscratch内核栈相关的汇编。学长如果觉得ok的话，我可以做一些修改，稍后提交pr。

非常感谢，这个涉及到多个分支，我来改吧

**Comment by wyfcyx** [comment]
这里提醒大家一定不要忘记加 `.altmarco`，不然会造成奇妙的编译错误。
