### ISSUE TITLE
关于Lab1部分文档中代码缺失或文件路径错误，导致最终无法正常运行的问题

### ISSUE THREAD

**Issue by yukiiiteru** [rcore-os/rCore-Tutorial#61]
### 涉及文件

* `docs/lab-1/guide/part-3.md` （代码缺失）
* `docs/lab-1/guide/part-4.md` （文件路径错误）
* `docs/lab-1/guide/part-5.md` （代码缺失）
* `docs/lab-1/guide/part-6.md` （代码缺失）

### 相关段落

* `docs/lab-1/guide/part-3.md`中，代码缺少以下部分：

  ```rust
  use core::fmt;
  ```

  ```rust
  /// 格式化输出
  ///
  /// # Example
  ///
  /// ```rust
  /// println!("{:x?}", Context);   // {:x?} 表示用十六进制打印其中的数值
  /// ```
  impl fmt::Debug for Context {
      fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
          f.debug_struct("Context")
              .field("registers", &self.x)
              .field("sstatus", &self.sstatus)
              .field("sepc", &self.sepc)
              .finish()
      }
  }
  ```

* `docs/lab-1/guide/part-4.md`中，以下文件路径错误：

  `os/src/interrupt.asm`应为`os/src/interrupt/interrupt.asm`

* `docs/lab-1/guide/part-5.md`中，代码缺少以下部分：

  ```rust
  use riscv::register::scause::Scause;
  ```

* `docs/lab-1/guide/part-6.md`中，代码缺少以下部分：

  ```rust
  use riscv::register::{
      scause::{Exception, Interrupt, Scause, Trap},
      sie, stvec,
  };
  ```

### 遇到问题

* 若参照`part-3.md`中的写法，会导致`src/interrupt/handler.rs`中`fault`函数报错，原因为：`context`无法被format
* 若参照`part-4.md`中的写法，会导致`src/interrupt/handler.rs`中`global_asm!(include_str!("./interrupt.asm"));`语句报错，原因为：找不到文件
* 若参照`part-5.md`中的写法，会导致`src/interrupt/handler.rs`中`handle_interrupt`函数报错，原因为：找不到`Scause`类型
* 若参照`part-5.md`中的写法，会导致`src/interrupt/handler.rs`中多处报错，多个类型及crate找不到

以上修改均参考[rCore-Tutorial lab-1分支](https://github.com/rcore-os/rCore-Tutorial/tree/lab-1/)，已提交Pull Request #58

**Comment by jwnhy** [comment]
悄咪咪说一句后面其实有更多，建议直接翻看 `os` 目录底下的源代码。

**Comment by Tuyixiang** [comment]
已在 #58 中答复
