### ISSUE TITLE
关于 Lab2 动态内存分配 一节中思考题的探讨

### ISSUE THREAD

**Issue by yukiiiteru** [rcore-os/rCore-Tutorial#69]
### 思考：动态分配的内存地址在哪个范围里？

[Lab2 动态内存分配](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-2/guide/part-1.html)

### 参考答案

在 `.bss` 段中，因为我们用来存放动态分配的这段是一个静态的没有初始化的数组，算是内核代码的一部分。

### 个人理解

动态分配的内存应该在堆中吧，而且在“调整内存布局”一节中关于`.bss`段及`Heap`段的解释为：

> .bss 段：存放被初始化为 0 的可读写数据，与 .data 段的不同之处在于我们知道它要被初始化为 0，因此在可执行文件中只需记录这个段的大小以及所在位置即可，而不用记录里面的数据，也不会实际占用二进制文件的空间
>
> Heap：堆，用来支持程序运行过程中内存的动态分配，比如说你要读进来一个字符串，在你写程序的时候你也不知道它的长度究竟为多少，于是你只能在运行过程中，知道了字符串的长度之后，再在堆中给这个字符串分配内存

在Lab2这一节的代码中，有一段

```rust
    let v = Box::new(5);
```

我用`gdb`调试输出，也可以看到该变量的位置是在堆空间以上的：

```gdb
(gdb) print v
$1 = (*mut i32) 0x80a1c960 <os::memory::heap::HEAP_SPACE+8388600>
```

其它变量可以用`gdb`输出，但无法看到在内存中的位置

而且我在维基百科上查到：

> 在采用段式内存管理的架构中，BSS段（bss segment）通常是指用来存放程序中未初始化的全局变量的一块内存区域。BSS是英文Block Started by Symbol的简称。BSS段属于静态内存分配。.bss section 的空间结构类似于 stack

结合以上，我认为 `.bss` 段是存放全局静态变量的

所以为什么参考答案说动态分配的内存在 `.bss` 段中呢？

### 参考文献

* [Lab0 调整内存布局](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-0/guide/part-6.html)
* [BSS段 - 维基百科](https://zh.wikipedia.org/wiki/BSS%E6%AE%B5)

**Comment by leonardodalinky** [comment]
感觉怪怪的。这一章的动态内存部分，是为了提供一个内核堆空间为后面的物理页面分配做下手。
个人认为，这里的.bss段就是为了充当一个在内核初始化阶段中的稳定的临时堆空间。因为我们在之后的各种操作中，都需要用到动态内存的分配，就比如Vec等数据结构。所以我们需要利用rust的特性，来指定一个空间作为Vec等数据结构的内存使用处。可以认为，.bss段在这里就是HEAP。
它和之前的c语言等其他已经适配了系统api的编程不同，因为那些语言已经可以直接通过brk等系统函数调用调整堆空间。
但在这里我们还在写系统，且并没有实现进程的概念，更没有那些调节堆空间的概念。为了简单起见，分配一个.bss充当堆，合情合理。
至于你说的内存地址在堆上，可能是有点混淆了概念，毕竟这个.bss段现在就是堆空间。
估算了一下，你那个变量的地址应该在0x80200000处偏移9M的大小（我们的内核从这个地址被qemu加载），综合考虑.bss段中8M的堆空间和.text和.rodata区的空间，应该还是可以认为这个变量的地址在堆中。
如果有错，还望指正。

**Comment by jwnhy** [comment]
这里用 .bss 段是一个不得已之举吧，因为如果如果需要用到 `Vec` 等特性就得开一块内存空间给内核用，然后物理内存页分配如果有了 `Vec` 会好写很多。

你这里写的 `.bss` 段是静态内存空间其实更多的是对于用户程序，而我们现在只有裸金属机。

其实，放哪都可以，只要能通过页表找到，并且有正确的权限，以及后续不再使用那块内存即可。

也可以把 `MEMORY_END` 往前移一点作为这块地址空间，总之很自由。

具体实现可以参考 Wrting an OS in Rust 2nd Edition，里面对堆的处理就很灵活。

**Comment by yukiiiteru** [comment]
谢谢楼上两位的解答，我有点理解了。

如果是在用户程序内，`.bss`段和`HEAP`段是明确区分开的，但是在内核中，为了简单起见，暂时用`.bss`段充当堆空间，是这样吧

**Comment by Tuyixiang** [comment]
好问题，已加入实验三题目中（WIP）

**Comment by chibinz** [comment]
在做lab2的时候，关于.bss段有一些疑惑……

操作系统在使用自己的`.bss`段之前为何不置0？
通常情况下，操作系统会给bss段的变量分配零页。但是这里是我们自己写操作系统，操作系统作为第一个运行的程序（不考虑bootloader），在使用bss段的变量之前应该先清零。然而在使用过程中，即使在没有手动置零的情况下也能正常运行。自己猜测有三种可能的原因：
1. QEMU默认未初始化的内存值为0。
2. 由于Rust RAII的特性，即使在no_std的情况下也会在变量使用之前对它进行初始化。
3. 这里的bss段只是作为操作系统随意分配的一块内存使用，初始值并不重要。/ 内核的正常运行不依赖于.bss段置零，所以没有发生错误。

不知道同学们有什么想法？
