### ISSUE TITLE
实验一文档的一些谬误

### ISSUE THREAD

**Issue by greatoyster** [rcore-os/rCore-Tutorial#73]
期望输出应该没有"hello rcore tutorial!"了
原文在Lab01->进入中断处理流程->触发中断

——————————————————————
——————————————————————
os/src/main.rs
...
mod interrupt;
...

/// Rust 的入口函数
///
/// 在 `_start` 为我们进行了一系列准备之后，这是第一个被调用的 Rust 函数
pub extern "C" fn rust_main() -> ! {
    // 初始化各种模块
    interrupt::init();

    unsafe {
        llvm_asm!("ebreak"::::"volatile");
    };

    unreachable!();
}
运行一下，可以看到 ebreak 导致程序进入了中断处理并退出，而没有执行到后面的 unreachable!()：

运行输出
Hello rCore-Tutorial!
mod interrupt initialized
panic: 'Interrupted: Exception(Breakpoint)'

——————————————————————
——————————————————————

**Comment by jwnhy** [comment]
建议直接Fork仓库修改后PR

**Comment by Tuyixiang** [comment]
感谢汇报，这个我已经在工作分支上修改
