### ISSUE TITLE
如何用rust表示c语言的某个结构

### ISSUE THREAD

**Issue by Wintersweet0** [rcore-os/rCore-Tutorial#74]
C语言中

`char *states[] = {"California", "Oregon", "Washington", "Texas"};`

这种结构如何用rust合适地表示呢
个人觉得用Vec实现可能比较方便？求指教

**Comment by greatoyster** [comment]
确实，你可以试着用Vec<&str>，也可以直接用vec!["califonia", ...........]

**Comment by yukiiiteru** [comment]
```rust
let states = vec!["California", "Oregon", "Washington", "Texas"];
```

**Comment by luojia65** [comment]
如果常量的话，可以用`let states = ["California", "Oregon", "Washington", "Texas"];`
