### ISSUE TITLE
增加对于address.rs的框架性的概述

### ISSUE THREAD

**Issue by Lincyaw** [rcore-os/rCore-Tutorial#81]
由于在看源码的时候, 发现很多函数都是在address.rs里实现的。而自己在看的时候发现这些函数都是环环相扣的，故写了一点对于这些函数之间联系的概述，可以更好地让看源码的人认识到这个文件的框架。可能复制会出现问题，所以我上传了下面这些的源码

四大基本类型:
`VirtualAddress`

`PhysicalAddress`

`VirtualPageNumber`

`PhysicalPageNumber`

1. mut指针和const指针可以通过`from`变为`VirtualAddress`

2. `VirtualPageNumber`和`PhysicalPageNumber`可以通过`from`互相转换

3. `address.rs`中实现了两个宏, 第一个宏为基本类型添加了`From trait`, 可以从页号变为地址也可以从地址变为页号（物理虚拟都可以）

4. 第二个宏为四个基本类型重载了一些算术运算的操作符

   

   万物之源`VirtualAddress`函数:

   ```rust
   pub fn deref<T>(self) -> &'static mut T
   pub fn page_offset(&self) -> usize
   ```

   `PhysicalAddress`函数:

   ```rust
   pub fn deref_kernel<T>(self) -> &'static mut T //转变为虚拟地址后调用虚拟地址的deref
   pub fn page_offset(&self) -> usize
   ```

   `VirtualPageNumber`函数:

   ```rust
   pub fn deref(self) -> &'static mut [u8; PAGE_SIZE] //转变为虚拟地址之后调用虚拟地址的deref
   pub fn levels(self) -> [usize; 3] //得到一、二、三级页号
   ```

   `PhysicalPageNumber`函数:

   ```rust
   pub fn deref_kernel(self) -> &'static mut [u8; PAGE_SIZE] //转变为物理地址之后调用物理地址的deref_kernel()函数,这个函数里又把物理地址变为虚拟地址,再调用虚拟地址的deref. 套娃石锤
   ```

   
[address.txt](https://github.com/rcore-os/rCore-Tutorial/files/4929286/address.txt)

**Comment by luojia65** [comment]
其实这儿（包括OpenSBI和SBI规范的设计）有个bug，就是物理地址是能超过usize长度的，比如Sv32下usize只有32位，物理地址却能到34位。
不过我们内核里用途很有限，就暂时不考虑这个，假设dtb的物理地址只能在64位/32位范围以内差不多了
