### ISSUE TITLE
关于Lab2和Lab3中内存分配的一些问题

### ISSUE THREAD

**Issue by SKTT1Ryze** [rcore-os/rCore-Tutorial#82]
### Lab2和Lab3中实现的内存分配好像每次只能分配一页？
下面是分配器代码：  
```Rust
/// 使用栈结构实现分配器
///
/// 在 `Vec` 末尾进行加入 / 删除。
/// 每个元素 tuple `(start, end)` 表示 [start, end) 区间为可用。
pub struct StackedAllocator {
    list: Vec<(usize, usize)>,
}

impl Allocator for StackedAllocator {
    fn new(capacity: usize) -> Self {
        Self {
            list: vec![(0, capacity)],
        }
    }

    fn alloc(&mut self) -> Option<usize> {
        if let Some((start, end)) = self.list.pop() {
            if end - start > 1 {
                self.list.push((start + 1, end));
            }
            Some(start)
        } else {
            None
        }
    }

    fn dealloc(&mut self, index: usize) {
        self.list.push((index, index + 1));
    }
}
```
从这个分配器代码看来每次分配只能获得一页内存。  
但为什么不实现一次性分配一定大小的内存呢？是因为没必要，还是在rCore-Tutorial里面没实现呢？  

### 上面这个分配器算法实现好像有点问题？
在上面代码中可以看到，每次从 list 中 pop 出一个 (start, end) ，如果 end - start > 1 就从这个对中分配出一个 (start, start + 1)，(start + 1, end)入栈。这是 alloc 的做法。  
再来看看 dealloc 的做法：回收内存 (index, index + 1)， 把 (index, index + 1) 进栈。  
结合 alloc 的实现我有一个疑问：那这样进栈的 (index, index + 1) 岂不是不能再被分配出去了？因为 index + 1 -index = 1 不符合 end - start > 1 的条件，实现中也没有任何方法让它和剩余的元素合并。这样这个 (index, index + 1) 不是就一直无法被重新分配了吗？

**Comment by SKTT1Ryze** [comment]
额，上面的第二个问题解决了，是我理解代码错了。大家不用理会了。

**Comment by SKTT1Ryze** [comment]
另外大家对Lab2和Lab3有什么改进的思路吗。一直没什么头绪，但也不想什么都不做。

**Comment by chibinz** [comment]
谈一谈自己的理解。
Lab 2 里面实现了两个Allocator，一个是memory/heap.rs里的HEAP，另一个是memory/frame/allocator里面的FRAME_ALLOCATOR，两者的用途不太一样。

HEAP的分配空间HEAP_SPACE是一个全局变量，位于.bss段，其实kernel的一部分。如果你做一下objdump或者运行时打印一下地址会发现，HEAP_SPACE位于kernel_start与kernel_end之间。把HEAP称作堆可能不太确切，个人认为更准确的名字应该叫做**操作系统自用堆**，方便操作系统存一些动态的数据结构。HEAP因为标记了global_allocator, 分配内存的时候可以直接用alloc::vec::Vec, alloc::boxed:Box, 免去了手动调用alloc和dealloc方法的麻烦。分配的颗粒度上小到一个字节，大到几千个元素的vector都可以。分配的算法封装在buddy_system_allocator这个crate里面。简单的来说就是对内存进行二分，把相近大小的数据放在一起以减少内存的碎片化。

FRAME_ALLOCATOR开始分配内存的地址位于kernel_end后面。从kernel_end的ceiling一直到0x88000000都是FRAME_ALLOCATOR可用的空间。如果不够的话还可以在qemu的设置里面调。FRAME_ALLOCATOR分配的内存是**给用户程序用的**。分配的颗粒度是一个页, 大小为4KiB。与HEAP不同，对页的分配对齐有要求，一个页的起始地址的低12位必须为零，也就是16进制最低三位为0x000。这些并不是rCore的系统设计，而是RISC-V硬件上的要求。注意到RISC-V Privileged ISA Specification 规定虚拟地址和物理地址的低12位都是offset，这个确定了物理页与虚拟页的大小相等且必须是2^12 Byte = 4KiB。如果这里物理页的分配不定大小的话后面虚拟页到物理页映射关系会非常麻烦。分配的算法在algorithm/src/allocator里面，因为每次分配大小是固定的，所以不存在外部碎片化问题，算法会简单很多。

在FRAME_ALLOCATOR的基础上实现任意大小的内存分配也是可以的，不过kernel已经有自己任意大小内存allocator了，再多一个没有必要。用户程序需要任意大小内存分配的话可以自己写一个。

Lab 3 做的是虚拟页到物理页的映射。虚拟页不存在分配问题，被映射到物理页之后才是一个valid的虚拟页，读写不会产生page fault。

不知道有没有回答你的问题。😅

**Comment by SKTT1Ryze** [comment]
非常感谢@chibinz

**Comment by SKTT1Ryze** [comment]
问题已经解决，麻烦学长@Tuyixiang关闭该issue，谢谢
