### ISSUE TITLE
Lab4 实验指导文档中可能存在的一些问题

### ISSUE THREAD

**Issue by yunwei37** [rcore-os/rCore-Tutorial#95]
### 涉及文件
- `docs/lab-4/guide/part-1.md`
- `docs/lab-4/guide/part-3.md`

### 相关段落

在 part1 中对 thread 结构体的定义如下：

[链接](https://github.com/rcore-os/rCore-Tutorial/blob/master/docs/lab-4/guide/part-1.md#%E7%BA%BF%E7%A8%8B%E7%9A%84%E8%A1%A8%E7%A4%BA)

```rs
/// 线程的信息
pub struct Thread {
    /// 线程 ID
    pub id: ThreadID,
    /// 线程的栈
    pub stack: Range<VirtualAddress>,
    /// 所属的进程
    pub process: Arc<RwLock<Process>>,
    /// 用 `Mutex` 包装一些可变的变量
    pub inner: Mutex<ThreadInner>,
}

/// 线程中需要可变的部分
pub struct ThreadInner {
    /// 线程执行上下文
    ///
    /// 当且仅当线程被暂停执行时，`context` 为 `Some`
    pub context: Option<Context>,
    /// 是否进入休眠
    pub sleeping: bool,
    /// 是否已经结束
    pub dead: bool,
    /// 打开的文件
    pub descriptors: Vec<Arc<dyn INode>>,
}
```

这一部分和 part3 中如下代码所使用的结构体定义似乎并不兼容：[链接](https://github.com/rcore-os/rCore-Tutorial/blob/master/docs/lab-4/guide/part-3.md#%E4%B8%8A%E4%B8%8B%E6%96%87-context-%E7%9A%84%E4%BF%9D%E5%AD%98%E5%92%8C%E5%8F%96%E5%87%BA)

```rs
/// 发生时钟中断后暂停线程，保存状态
pub fn park(&self, context: Context) {
    // 检查目前线程内的 context 应当为 None
    let mut slot = self.context.lock();
    assert!(slot.is_none());
    // 将 Context 保存到线程中
    slot.replace(context);
}
```

以及：

```rs
/// 准备执行一个线程
///
/// 激活对应进程的页表，并返回其 Context
pub fn run(&self) -> *mut Context {
    // 激活页表
    self.process.read().memory_set.activate();
    // 取出 Context
    let parked_frame = self.context.lock().take().unwrap();
```

### 遇到问题

这两个部分的代码似乎来源并不一致；part3中间的代码应当是在 lab4 中的过渡性实现，而 part1中所采用的定义部分是所有教程结束之后的结果，也包含了文件系统的一些内容。另外，由于lab4分支中也是所有教程结束之后的包含用户进程的实现，和实验指导文档中的差异较大，因此好像也并没有能够参照实现的代码。

### 涉及文件

- `docs/lab-4/guide/part-5.md`

### 相关段落

[链接](https://github.com/rcore-os/rCore-Tutorial/blob/master/docs/lab-4/guide/part-5.md#%E8%BF%90%E8%A1%8C)

在main函数中：

```rs
/// Rust 的入口函数
///
/// 在 `_start` 为我们进行了一系列准备之后，这是第一个被调用的 Rust 函数
#[no_mangle]
pub extern "C" fn rust_main() -> ! {
   .......
    PROCESSOR.get().run();
}
```

在调度器这里：

```rs
lazy_static! {
    /// 全局的 [`Processor`]
    pub static ref PROCESSOR: Lock<Processor> = Lock::new(Processor::default());
}

```
### 遇到问题

[https://github.com/rcore-os/rCore-Tutorial/issues/94](https://github.com/rcore-os/rCore-Tutorial/issues/94)

就像昨天这个issue提及的那样，如果参照文档进行实现的话，有可能导致多线程运行的死锁；可能需要更改 mian 函数中或者 Processor 的实现（就像lab-4分支那样）二者之一

**Comment by Tuyixiang** [comment]
感谢提出问题

**Comment by shiweiwww** [comment]
我补充一个，sscratch这个内核栈应该被初始化，但找了下没有，只有第一次时钟中断时候后才设置好，sscratch这个是不是一开始初始化好更合适？

**Comment by Tuyixiang** [comment]
> 我补充一个，sscratch这个内核栈应该被初始化，但找了下没有，只有第一次时钟中断时候后才设置好，sscratch这个是不是一开始初始化好更合适？

应该是在第一次调用 `__restore` 时赋值的
