### ISSUE TITLE
rCore的Into trait 是在哪里定义的？

### ISSUE THREAD

**Issue by ZenusZhang** [rcore-os/rCore-Tutorial#96]
查找[官方文档](https://doc.rust-lang.org/std/convert/trait.Into.html) 可知，Into是std里定义的trait，可是我们不是已经禁用了std吗？那么为什么还能够直接使用？

**Comment by Lincyaw** [comment]
定义了From之后自动会实现into

**Comment by ZenusZhang** [comment]
> 定义了From之后自动会实现into

我在整个文件夹（rCore-Tutorial lab2）中搜索“From” 并没有发现`pub trait From` 这个语句，在rust文档中搜索“From"也只有`Trait std::convert::From`这样一句。但是我们在main.rs中已经说明了 `#![no_std]` 。那么rCore中的From是在哪里定义的呢？

**Comment by Tuyixiang** [comment]
`core::convert::From`，不知道为什么文档里面搜索不显示这个，但是确实有
