### ISSUE TITLE
关于中断分类标准的问题

### ISSUE THREAD

**Issue by stellarkey** [rcore-os/rCore-Tutorial#97]
### 标题
rCore-Tutorial lab1中将**中断**分类为：异常、**陷阱**、**硬件中断**。

而清华操作系统课上则分类为：异常、**系统调用**（软中断）、**中断**。

这两类称谓虽然大体上可以一一对应，但学术上更倾向于怎么称呼呢？这两种不同的描述方式，会不会导致有些时候概念理解上出现偏差？

**Comment by am009** [comment]
我觉得只要理解好了自己用到的的指令集中对这些中断的区分, 就不会有什么理解的偏差吧.

**Comment by chibinz** [comment]
OS是一门非常注重实践的学科。操作系统的产生，源于工业界（IBM）对于管理日益复杂软件和硬件的诉求。像interrupt, trap, exception, syscall 这样的名词很有可能是某个工程师在实践、摸索过程中发明出来的。由于只是方便工程师之间沟通，所以没有严格的定义，可以互换着使用。学术界早期对于操作系统的研究应该是落后于工业界，这些概念adopt过来之后不同人不同课本有不同的定义。

碰巧我们学校OS课对于这些概念的定义和tutorial里面也不太一样。我在lab1的学习记录里面对于这个问题也进行了思考。中断分为硬中断和软中断。硬中断是外部的，asynchronous的，可以在某一条指令执行中间产生，由cpu保证atomicity。软中断具体由某一条指令造成，是synchronous的，可以分为两类。一类是主动转让控制权给OS，通常被称为syscall或者trap。另一类是非主动的，被称为exception。他们共同的特征是会发生上下文转换（context switch），执行环境特权级别的提升。
- interrupt
  - hardware interrupt (external, async)
  - software interrupt (internal, sync)
    - syscall/trap (voluntarily yield to os)
    - exception (involuntarily caught by os)

trap陷阱这个翻译有些直，陷入可能更好的体现控制权主动的转让。

个人的一些薄见，不一定准确😂。如果你想要权威的回答的话可以去问问陈渝老师。

**Comment by stellarkey** [comment]
> 
> 
> OS是一门非常注重实践的学科。操作系统的产生，源于工业界（IBM）对于管理日益复杂软件和硬件的诉求。像interrupt, trap, exception, syscall 这样的名词很有可能是某个工程师在实践、摸索过程中发明出来的。由于只是方便工程师之间沟通，所以没有严格的定义，可以互换着使用。学术界早期对于操作系统的研究应该是落后于工业界，这些概念adopt过来之后不同人不同课本有不同的定义。
> 
> 碰巧我们学校OS课对于这些概念的定义和tutorial里面也不太一样。我在lab1的学习记录里面对于这个问题也进行了思考。中断分为硬中断和软中断。硬中断是外部的，asynchronous的，可以在某一条指令执行中间产生，由cpu保证atomicity。软中断具体由某一条指令造成，是synchronous的，可以分为两类。一类是主动转让控制权给OS，通常被称为syscall或者trap。另一类是非主动的，被称为exception。他们共同的特征是会发生上下文转换（context switch），执行环境特权级别的提升。
> 
>     * interrupt
>       
>       * hardware interrupt (external, async)
>       * software interrupt (internal, sync)
>         
>         * syscall/trap (voluntarily yield to os)
>         * exception (involuntarily caught by os)
> 
> 
> trap陷阱这个翻译有些直，陷入可能更好的体现控制权主动的转让。
> 
> 个人的一些薄见，不一定准确😂。如果你想要权威的回答的话可以去问问陈渝老师。

感谢回答~
