### ISSUE TITLE
lab3汇编代码entry.asm理解

### ISSUE THREAD

**Issue by shiweiwww** [rcore-os/rCore-Tutorial#98]
### 修改内核起始地址为0xffff_ffff_80xxxx后，entry.asm中%hi(boot_page_table)是读取boot_page_table的高20位，objdump -x查看boot_page_table地址为0xffffffff80212000，%hi(boot_page_table)不应该是0xffff吗？为什么反汇编后发现是0x80212
汇编代码
```
    lui t0, %hi(boot_page_table)
    li t1, 0xffffffff00000000
```
反汇编
```
    ffffffff80200000: b7 f2 20 80          	lui	t0, 0x80212
    ffffffff80200004: 7d 53                	addi	t1, zero, -1
```

**Comment by Tuyixiang** [comment]
`%hi` `%lo` 的设计是 32 位的，所以这里的 `%hi` 指的就是 [12,32) 位 `0x80212`。此时最高位为 1，所以对于 64 位寄存器，高 32 位就都填 1

**Comment by shiweiwww** [comment]
多谢多谢，懂了
