### ISSUE TITLE
lab3 页表的理解

### ISSUE THREAD

**Issue by shiweiwww** [rcore-os/rCore-Tutorial#99]

**Comment by chibinz** [comment]
是具体哪一点不太明白？是概念上，还是tutorial里面实现上的？如果是前者的话可以看看清华操作系统的网课。tutorial里面页表的实现还是有点复杂的，封装的层数比较多。如果不问的细致一些的话，大伙可能在issue里面一时半会儿解释不清楚。😂😆

**Comment by stellarkey** [comment]
首先，使用页表的原因是因为想获得更大的虚拟地址空间，然后是实现虚实页之间的可自定义映射关系。

比如对于一个二级页表系统，虚拟地址的的格式通常为 ABD，而物理地址为 CD。

A、B、C就好在页表里就是页表内部的项的自然编号。

首先在一级页表（又叫做页目录）中查找A，这个过程其实就是把A作为偏移量找到对应的页表项。找到了一级页表项，
一级页表内就记载了某一个对应的二级页表的位置。

我们需要在这个二级页表中，查找B。同理，找到了二级页表项，二级页表内就记载了从ABD到CD的一个映射关系（最底级的页表一定是存储这个映射关系）。

那么我们就找到了对应的物理地址。

网上也有很多页表相关的介绍，比如：https://blog.csdn.net/Doctor_xiong/article/details/79534505。

**Comment by dingiso** [comment]
我的理解比较通俗，大致是这样的。

### 首先： 为什么要用到虚拟地址？
简单理解，这是为了方便程序编写者的一种方法。比如我的程序想要运行在这个操作系统上， 我希望不需要考虑操作系统的实际内存情况，难道我还要看一下操作系统的代码，或翻一下手册么？（😀） ， 我希望我的程序用的就是从 `0x1` 开始的连续地址，那么这个 `0x1` 就是虚拟地址。

### 页表：
但是在操作系统中，实际运行时是需要使用实际物理地址的，那么我们如何推算物理地址呢，我们可以将这种（虚拟地址-物理地址）看作一种函数（映射）关系
`f (虚拟地址）= 物理地址`   在存储时 就有了两种储存的方法，

1. 第一种 我们将这个 `f` 函数（简单理解是个线性的）关系储存下来 - 也就是 最开始[修改内核](https://rcore-os.github.io/rCore-Tutorial-deploy/docs/lab-3/guide/part-2.html) 中使用的方法， 只需要统一加一个 偏移量即可。
2.  第二种 我们将每一个 （虚拟地址-物理地址） 也就  (x,y) 按对存储起来，通过查找 虚拟地址，便能获得相应的物理地址。

第二种方法便是我们所说的页表 ， 他是一（多）张，存储这种关系的表，通过查表便能完成 查找物理地址的任务。

> 而且，虚拟地址也是对物理的地址的一种封装方法，可以实现内核对物理地址的权限管理，也就是我们在页表项的标志位，假设我不希望系统内核所在的地址被其他人写入其他内容，我只需要在页表项上

### 多级页表：
这种方法主要是为了节省内存，同时可以方便我们不用跨物理页去查询这张表。那么他为什么可以节省内存呢？ 
**举个小栗子：**  内核代码在虚拟地址里 是 `0xffffffff80200000` ， 在实际物理地址是 `0x80200000` ， 在普通页表中我要这么存储， `(0xffffffff80200000,0x80200000,flag)` 这样的。同样在表示内核以 0xffffffff 开头的虚拟地址还有很多，这样会无形中增加很多的空间开销，但我们知道不断存储 `0xffffffff` 是冗余的。所以我们利用分级的方法，可以把页表变成下面的形式（理解方法）：

- 二级页表 `（0xffffffff（虚拟地址的高位），存储下面一级页表的物理页号（首地址） ）`
- 一级页表 `（0x80200000（低位），0x80200000（物理地址））`
通过二级页表查找到一级页表的存储位置，再通过低位找到对应的物理地址。

**那么**我们实际上对于所有 以开头 `0xffffffff` 开头的虚拟地址，二级页表中永远只有一个页表项，这就节省了原来每次都要把他写上的空间。

这是关于页表比较通俗的理解，可能有些啰嗦，但我尽量用通俗的语言，多级页表尽量还原实际，方便再看书的时候理解，
**代码方面**结合 上一章的内容 ， 封装方式类似。

**Comment by greatoyster** [comment]
你可以参照这个链接，上面的内容我认为比较简洁明了
https://www.wikiwand.com/zh-sg/%E5%88%86%E9%A0%81%E8%A1%A8
